export const CATEGORIES = {
   Animals: [
    { word: "Lion", hints: ["Pride", "Savanna", "Dominion"] },
    { word: "Elephant", hints: ["Memory", "Ivory", "Herd"] },
    { word: "Giraffe", hints: ["Canopy", "Altitude", "Spots"] },
    { word: "Penguin", hints: ["Tuxedo", "Colony", "Current"] },
    { word: "Kangaroo", hints: ["Marsupial", "Outback", "Spring"] },
    { word: "Dolphin", hints: ["Pod", "Echo", "Intelligence"] },
    { word: "Tiger", hints: ["Solitary", "Ambush", "Jungle"] },
    { word: "Bear", hints: ["Hibernate", "Forage", "Territory"] },

    { word: "Wolf", hints: ["Pack", "Howl", "Hierarchy"] },
    { word: "Fox", hints: ["Cunning", "Rust", "Dusk"] },
    { word: "Owl", hints: ["Nocturnal", "Wisdom", "Silence"] },
    { word: "Eagle", hints: ["Soar", "Apex", "Vision"] },
    { word: "Shark", hints: ["Predator", "Current", "Frenzy"] },
    { word: "Crocodile", hints: ["Ambush", "River", "Ancient"] },
    { word: "Panda", hints: ["Bamboo", "Solitude", "Conservation"] },
    { word: "Horse", hints: ["Gallop", "Saddle", "Stable"] },
    { word: "Rabbit", hints: ["Burrow", "Timid", "Prolific"] },
    { word: "Snake", hints: ["Venom", "Shed", "Slither"] },
    { word: "Frog", hints: ["Amphibian", "Metamorphosis", "Lily"] },
    { word: "Octopus", hints: ["Ink", "Tentacle", "Camouflage"] },
    { word: "Peacock", hints: ["Display", "Plumage", "Vanity"] },
    { word: "Bat", hints: ["Nocturnal", "Cavern", "Ultrasound"] },
    { word: "Zebra", hints: ["Herd", "Contrast", "Savanna"] },
    { word: "Whale", hints: ["Migration", "Depth", "Song"] },
    { word: "Leopard", hints: ["Rosette", "Stealth", "Arboreal"] }
  ],
  Food: [
    { word: "Pizza", hints: ["Slice", "Oven", "Sharing"] },
    { word: "Sushi", hints: ["Minimalism", "Wasabi", "Precision"] },
    { word: "Burger", hints: ["Stack", "Grill", "Wrapper"] },
    { word: "Taco", hints: ["Fold", "Street", "Salsa"] },
    { word: "Ice Cream", hints: ["Melt", "Cone", "Indulgence"] },
    { word: "Pasta", hints: ["Boil", "Alente", "Twirl"] },
    { word: "Salad", hints: ["Fresh", "Tossed", "Dressing"] },
    { word: "Steak", hints: ["Sear", "Marble", "Rare"] },

    { word: "Sandwich", hints: ["Layers", "Portable", "Crust"] },
    { word: "Soup", hints: ["Simmer", "Broth", "Ladle"] },
    { word: "Curry", hints: ["Spice", "Simmer", "Aroma"] },
    { word: "Pancake", hints: ["Flip", "Stack", "Syrup"] },
    { word: "Chocolate", hints: ["Cocoa", "Bitter", "Indulgence"] },
    { word: "Cheesecake", hints: ["Dense", "Crust", "Chill"] },
    { word: "Fries", hints: ["Crisp", "Salt", "Side"] },
    { word: "Ramen", hints: ["Broth", "Steam", "Slurp"] },
    { word: "Dumpling", hints: ["Folded", "Steam", "Filling"] },
    { word: "Omelette", hints: ["Whisk", "Fold", "Skillet"] },
    { word: "Donut", hints: ["Glaze", "Ring", "Fry"] },
    { word: "Lasagna", hints: ["Layered", "Bake", "Ricotta"] },
    { word: "Croissant", hints: ["Flaky", "Butter", "Parisian"] },
    { word: "Popcorn", hints: ["Kernel", "Burst", "Cinema"] },
    { word: "Hot Dog", hints: ["Bun", "Stadium", "Mustard"] },
    { word: "Paella", hints: ["Saffron", "Pan", "Seafood"] },
    { word: "Nachos", hints: ["Shared", "Layered", "Cheese"] }
  ],
  Professions: [
    { word: "Doctor", hints: ["Diagnosis", "Rounds", "Prescription"] },
    { word: "Teacher", hints: ["Curriculum", "Mentor", "Assessment"] },
    { word: "Firefighter", hints: ["Rescue", "Alarm", "Ladder"] },
    { word: "Chef", hints: ["Palette", "Plating", "Kitchen"] },
    { word: "Police Officer", hints: ["Patrol", "Authority", "Badge"] },
    { word: "Artist", hints: ["Canvas", "Expression", "Medium"] },
    { word: "Musician", hints: ["Rhythm", "Harmony", "Performance"] },
    { word: "Pilot", hints: ["Altitude", "Cockpit", "Navigation"] },

    { word: "Engineer", hints: ["Blueprint", "Systems", "Optimization"] },
    { word: "Lawyer", hints: ["Advocate", "Litigation", "Statute"] },
    { word: "Journalist", hints: ["Deadline", "Source", "Headline"] },
    { word: "Architect", hints: ["Design", "Structure", "Drafting"] },
    { word: "Nurse", hints: ["Care", "Triage", "Shift"] },
    { word: "Scientist", hints: ["Hypothesis", "Experiment", "Research"] },
    { word: "Farmer", hints: ["Harvest", "Soil", "Seasonal"] },
    { word: "Mechanic", hints: ["Engine", "Repair", "Grease"] },
    { word: "Photographer", hints: ["Lens", "Exposure", "Frame"] },
    { word: "Dentist", hints: ["Enamel", "Drill", "Cavity"] },
    { word: "Programmer", hints: ["Syntax", "Compile", "Debug"] },
    { word: "Entrepreneur", hints: ["Venture", "Risk", "Startup"] },
    { word: "Actor", hints: ["Script", "Role", "Stage"] },
    { word: "Carpenter", hints: ["Timber", "Measure", "Joinery"] },
    { word: "Electrician", hints: ["Circuit", "Voltage", "Wiring"] },
    { word: "Therapist", hints: ["Session", "Listening", "Insight"] },
    { word: "Plumber", hints: ["Pipe", "Leak", "Drain"] },
    { word: "Barber", hints: ["Fade", "Trim", "Clipper"] }
  ],
  Countries: [
    { word: "Japan", hints: ["Archipelago", "Precision", "Sakura"] },
    { word: "Brazil", hints: ["Rainforest", "Samba", "Carnival"] },
    { word: "France", hints: ["Cuisine", "Revolution", "Elegance"] },
    { word: "Australia", hints: ["Outback", "Reef", "Isolation"] },
    { word: "Egypt", hints: ["Nile", "Dynasty", "Desert"] },
    { word: "Canada", hints: ["Maple", "Bilingual", "Tundra"] },
    { word: "Italy", hints: ["Renaissance", "Peninsula", "Opera"] },
    { word: "India", hints: ["Monsoon", "Bollywood", "Diversity"] },

    { word: "Germany", hints: ["Autobahn", "Efficiency", "Engineering"] },
    { word: "Mexico", hints: ["Mural", "Aztec", "Spice"] },
    { word: "China", hints: ["Dynasty", "Manufacturing", "Population"] },
    { word: "Spain", hints: ["Flamenco", "Iberian", "Siesta"] },
    { word: "Russia", hints: ["Vast", "Tundra", "Kremlin"] },
    { word: "South Africa", hints: ["Apartheid", "Safari", "Diversity"] },
    { word: "Greece", hints: ["Philosophy", "Mythology", "Aegean"] },
    { word: "Turkey", hints: ["Strait", "Bazaar", "Crossroads"] },
    { word: "Argentina", hints: ["Tango", "Pampas", "Patagonia"] },
    { word: "South Korea", hints: ["Kpop", "Peninsula", "Technology"] },
    { word: "Saudi Arabia", hints: ["Desert", "Petroleum", "Monarchy"] },
    { word: "Thailand", hints: ["Temple", "Tropical", "Elephant"] },
    { word: "Netherlands", hints: ["Canal", "Tulip", "Cycling"] },
    { word: "Switzerland", hints: ["Neutral", "Alps", "Banking"] },
    { word: "Indonesia", hints: ["Archipelago", "Volcano", "Biodiversity"] },
    { word: "Sweden", hints: ["Nordic", "Welfare", "Innovation"] },
    { word: "Vietnam", hints: ["Delta", "Motorbike", "Resilience"] },
    { word: "Peru", hints: ["Andes", "Inca", "Highland"] }
  ],
  "Famous People": [
    { word: "Albert Einstein", hints: ["Relativity", "Patent", "Theoretical"] },
    { word: "Marilyn Monroe", hints: ["Hollywood", "Icon", "Glamour"] },
    { word: "Leonardo da Vinci", hints: ["Polymath", "Renaissance", "Anatomy"] },
    { word: "Michael Jackson", hints: ["Pop", "Moonwalk", "Superstar"] },
    { word: "Cleopatra", hints: ["Dynasty", "Seduction", "Alliance"] },
    { word: "William Shakespeare", hints: ["Tragedy", "Verse", "Playwright"] },
    { word: "Elvis Presley", hints: ["Rock", "Graceland", "Charisma"] },
    { word: "Abraham Lincoln", hints: ["Union", "Emancipation", "Resolve"] },

    { word: "Napoleon Bonaparte", hints: ["Empire", "Exile", "Ambition"] },
    { word: "Mahatma Gandhi", hints: ["Nonviolence", "Independence", "Protest"] },
    { word: "Martin Luther King Jr.", hints: ["Dream", "Equality", "Oratory"] },
    { word: "Nelson Mandela", hints: ["Imprisonment", "Reconciliation", "Leadership"] },
    { word: "Marie Curie", hints: ["Radiation", "Discovery", "Persistence"] },
    { word: "Isaac Newton", hints: ["Gravity", "Calculus", "Principia"] },
    { word: "Steve Jobs", hints: ["Innovation", "Minimalism", "Visionary"] },
    { word: "Oprah Winfrey", hints: ["Media", "Influence", "Interview"] },
    { word: "Princess Diana", hints: ["Royalty", "Compassion", "Legacy"] },
    { word: "Muhammad Ali", hints: ["Boxing", "Confidence", "Rhythm"] },
    { word: "Frida Kahlo", hints: ["Portrait", "Pain", "Symbolism"] },
    { word: "Walt Disney", hints: ["Animation", "Imagination", "Empire"] },
    { word: "Christopher Columbus", hints: ["Voyage", "Exploration", "Controversy"] },
    { word: "Rosa Parks", hints: ["Bus", "Defiance", "Civilrights"] },
    { word: "Julius Caesar", hints: ["Senate", "Empire", "Assassination"] },
    { word: "Ada Lovelace", hints: ["Algorithm", "Vision", "Computation"] },
    { word: "Pablo Picasso", hints: ["Cubism", "Avantgarde", "Guernica"] },
    { word: "Mother Teresa", hints: ["Charity", "Missionary", "Compassion"] }
  ],
  Objects: [
    { word: "Clock", hints: ["Ticking", "Circular", "Deadline"] },
    { word: "Umbrella", hints: ["Canopy", "Drizzle", "Collapse"] },
    { word: "Mirror", hints: ["Reflection", "Vanity", "Glass"] },
    { word: "Key", hints: ["Access", "Metal", "Unlock"] },
    { word: "Scissors", hints: ["Shear", "Blades", "Precision"] },
    { word: "Chair", hints: ["Seated", "Legs", "Support"] },
    { word: "Telephone", hints: ["Ring", "Signal", "Conversation"] },
    { word: "Book", hints: ["Pages", "Spine", "Story"] },

    { word: "Candle", hints: ["Wax", "Flame", "Melt"] },
    { word: "Backpack", hints: ["Straps", "Carry", "Travel"] },
    { word: "Bottle", hints: ["Cap", "Container", "Pour"] },
    { word: "Knife", hints: ["Edge", "Slice", "Sharp"] },
    { word: "Laptop", hints: ["Portable", "Screen", "Keyboard"] },
    { word: "Glasses", hints: ["Lens", "Frame", "Focus"] },
    { word: "Wallet", hints: ["Fold", "Currency", "Pocket"] },
    { word: "Helmet", hints: ["Protect", "Impact", "Strap"] },
    { word: "Watch", hints: ["Wrist", "Dial", "Timepiece"] },
    { word: "Map", hints: ["Route", "Navigate", "Fold"] },
    { word: "Pillow", hints: ["Soft", "Rest", "Cushion"] },
    { word: "Camera", hints: ["Capture", "Lens", "Shutter"] },
    { word: "Notebook", hints: ["Paper", "Notes", "Spiral"] },
    { word: "Spoon", hints: ["Scoop", "Bowl", "Metal"] },
    { word: "Suitcase", hints: ["Travel", "Handle", "Luggage"] },
    { word: "Flashlight", hints: ["Beam", "Battery", "Darkness"] },
    { word: "Remote", hints: ["Control", "Buttons", "Distance"] },
    { word: "Ladder", hints: ["Rungs", "Climb", "Height"] },

    { word: "Compass", hints: ["Magnetic", "Direction", "North"] },
    { word: "Lantern", hints: ["Glow", "Portable", "Night"] },
    { word: "Hammer", hints: ["Impact", "Nail", "Force"] },
    { word: "Envelope", hints: ["Sealed", "Paper", "Message"] },
    { word: "Telescope", hints: ["Magnify", "Distant", "Observe"] },
    { word: "Hourglass", hints: ["Sand", "Inverted", "Measure"] },
    { word: "Coin", hints: ["Minted", "Currency", "Flip"] },
    { word: "Mask", hints: ["Conceal", "Identity", "Facade"] },
    { word: "Rope", hints: ["Tension", "Knot", "Fiber"] },
    { word: "Magnifying Glass", hints: ["Scrutiny", "Lens", "Enlarge"] },
    { word: "Briefcase", hints: ["Professional", "Latch", "Document"] },
    { word: "Anchor", hints: ["Weight", "Harbor", "Stability"] }
  ],
  Movies: [
    { word: "The Matrix", hints: ["Simulation", "Choice", "Awakening"] },
    { word: "Titanic", hints: ["Voyage", "Iceberg", "Tragedy"] },
    { word: "Star Wars", hints: ["Galaxy", "Legacy", "Rebellion"] },
    { word: "Jurassic Park", hints: ["Extinction", "Revival", "Chaos"] },
    { word: "Avatar", hints: ["Colonialism", "Alien", "Immersion"] },
    { word: "The Lion King", hints: ["Succession", "Exile", "Savanna"] },
    { word: "Jaws", hints: ["Predator", "Ocean", "Tension"] },
    { word: "Harry Potter", hints: ["Magic", "School", "Destiny"] },

    { word: "Avengers", hints: ["Alliance", "Sacrifice", "Superhero"] },
    { word: "Inception", hints: ["Dream", "Layers", "Subconscious"] },
    { word: "The Dark Knight", hints: ["Chaos", "Vigilante", "Duality"] },
    { word: "Frozen", hints: ["Sisters", "Winter", "Isolation"] },
    { word: "Spider-Man", hints: ["Responsibility", "Mask", "Agility"] },
    { word: "The Shawshank Redemption", hints: ["Hope", "Prison", "Freedom"] },
    { word: "Forrest Gump", hints: ["Journey", "Innocence", "History"] },
    { word: "Gladiator", hints: ["Arena", "Honor", "Vengeance"] },
    { word: "The Godfather", hints: ["Family", "Power", "Legacy"] },
    { word: "Interstellar", hints: ["Space", "Time", "Survival"] },

    { word: "3 Idiots", hints: ["Friendship", "Pressure", "Innovation"] },
    { word: "Dangal", hints: ["Wrestling", "Determination", "Fatherhood"] },
    { word: "PK", hints: ["Alien", "Religion", "Satire"] },
    { word: "Baahubali", hints: ["Kingdom", "Betrayal", "Epic"] },
    { word: "Lagaan", hints: ["Colonialism", "Cricket", "Defiance"] },
    { word: "Kabhi Khushi Kabhie Gham", hints: ["Family", "Wealth", "Emotion"] },
    { word: "Zindagi Na Milegi Dobara", hints: ["Friendship", "Travel", "Selfdiscovery"] },
    { word: "Chennai Express", hints: ["Journey", "Romance", "Comedy"] },
    { word: "Dilwale Dulhania Le Jayenge", hints: ["Tradition", "Romance", "Europe"] },
    { word: "Bajrangi Bhaijaan", hints: ["Border", "Child", "Compassion"] }
  ],
};

export type Category = keyof typeof CATEGORIES;

export const getRandomWord = (category: Category) => {
  const words = CATEGORIES[category];
  const randomWordObj = words[Math.floor(Math.random() * words.length)];
  const randomHint = randomWordObj.hints[Math.floor(Math.random() * randomWordObj.hints.length)];
  return { word: randomWordObj.word, hint: randomHint };
};
